klask_policy_inference_node:
  ros__parameters:
    # Model configuration
    weights_filename: "klask_ac_nn_v0.0.pth"  # Name of the model file to load from nn_weights folder
    weights_zip_url: "https://polybox.ethz.ch/index.php/s/joEoP8GgQbwmToW/download"  # URL to download weights zip
    device: "cpu"  # Options: "cpu", "cuda"
    
    # Board configuration
    board_width: 0.42   # meters
    board_height: 0.32  # meters
    
    # Player configuration
    player_side: "left"  # Options: "left", "right"
    
    # ROS topic configuration
    state_topic: "/board_state"
    cmd_vel_topic: "cmd_vel/left_player"
    
    # QoS settings
    subscription_queue_size: 1
    publisher_queue_size: 1
